### ISSUE TITLE
Editing name of shared place not possible.

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_shared_places#10]
When I will edit the name of a shared place clicking on the edit icon makes nothing. I cann change this name only using edit gedcom. Not a big problem - name changes are not very often.
![image](https://user-images.githubusercontent.com/60657963/79037845-d8df0880-7bd4-11ea-8669-8313452a4dbb.png)

Editing Name/Married name in an individual works fine.
![image](https://user-images.githubusercontent.com/60657963/79037855-f2805000-7bd4-11ea-82b6-739f6bcf850e.png)

Thanks.

Ladislav

**Comment by ric2016** [comment]
Fixed in the latest release.
