### ISSUE TITLE
Feature request: owners of a shared place

### ISSUE THREAD

**Issue by wp4711** [vesta-webtrees-2-custom-modules/vesta_shared_places#107]
Hi, I now use shared places for houses (eg. housenumber 1, street, village, region, country) 
now housnumber 1 is assigned to more individuals by the owner opition.
would like to have a tab in the shared place where all owners are listed (like the person and family tab) with the years. eg.
1700-1750 person 1
1750-1800 person 2
...
...
is it possible to do?

**Comment by ric2016** [comment]
I like the idea! This would be a good way to show the history of a place.

I'm not sure about this though:
> housnumber 1 is assigned to more individuals by the owner opition.

"Owner option" is an associate with relationship type "owner" - On specific facts and events? Can you give an example (GEDCOM snippet)?

**Comment by wp4711** [comment]
Ill try, this is the owner (german Besitz) information of an individua
![owner](https://user-images.githubusercontent.com/96334271/152650095-3fb80550-47c5-46f0-85a9-e2e0ca74ad84.png)
l

**Comment by ric2016** [comment]
Yes, that makes sense (it's just a tag that I never use, so I wasn't aware of it).

I'll have to check how to implement this feature in general, as there is currently no way to query the database directly for this kind of link from individual to place. So all individuals linked to a place will have to be checked for the respective information (which may take a while if there are a lot of them).

Also, other facts and events may also be useful in this context, not only owners:

Ich schreibe mal auf deutsch weiter: Bei Höfelisten u.ä. sind die Halbmeier usw. auf den Höfen ja nicht die eigentlichen Besitzer (jedenfalls z.B. in Norddeutschland), deswegen ist dort eher "Beruf" als "Besitz" zu verwenden. Also sollte man vielleicht die Arten der Fakten und Ereignisse, die dann für das neue Tab "Historie des Gemeinsamen Ortes" verwendet werden, konfigurierbar machen.

**Comment by wp4711** [comment]
Sehe ich genauso, somit könnte man eine sehr schöne Hofchronik machen. Das wäre ein echt super Feature.
Eventuell könnte man dann einen Bericht generieren, wo auch noch die Mediadateien und Notizen zum shared place dabei sind. Das wird dann aber vermutlich eine zu umfangreiche Aufgabe die auch nicht unmittelbar wichtig und notwendig ist. Die Grundidee ist aber sicher super. Man hätte endlich ein Programm das Haus - bzw. Hofchronik und gedcom / Stammbaum vereint.

**Comment by ric2016** [comment]
Ja, Reporting ist ein Thema für sich. Das Feature an sich werde ich sicher einbauen, ich muß noch schauen, ob erst mit webtrees 2.1 oder noch vorher.

Im Prinzip ist es sogar unabhängig von den Gemeinsamen Orten und könnte auch für 'normale' Orte realisiert werden (wenn man diese auch für einzelne Höfe etc. verwendet).

**Comment by wp4711** [comment]
Stimmt, ich verwende halt das Modul sehr gerne weil es sehr komfortabel ist. Reporting ist auch nicht so wichtig weil es (für mich) eigentlich eher wichtig ist, die Daten so kompakt und übersichtlich wie möglich zusammen zu haben. Ich habe vor kurzem eine Hauschronik gemacht und da hätte ich genau dieses Feature in einer Software gesucht. Leider vergeblich... Somit war ich gezwungen, meine eigentlich vorhandenen gedcom daten in excel zu transportieren. So bin ich auf die Idee gekommen. Solltest du dich ranmachen kannst du gerne Bescheid sagen, ich teste dann auch gern mit!

**Comment by wp4711** [comment]
Man könnte auch Geburten/Sterbedaten etc. dazugeben und durch an/abwählen dadurch eine vollständige Chronologie erhalten. Dann müsste in der Liste aber auch die Art des Ereignisses dabeistehen da es sonst unübersichtlich werden würde.

**Comment by ric2016** [comment]
So, es hat wegen der Umstellung auf webtrees 2.1 etwas gedauert ...

Eine erste Version dieser Funktionalität ist nun verfügbar (nur in webtrees 2.1.x, nicht im 2.0.x-Zweig). Siehe Reiter 'Place History' bei gemeinsamen Orten, das Gleiche auch für normale Orte in der Detailansicht in der Liste ('Ortshierarchie').

Offene TODOs:
* Ereignisarten erweitern und konfigurierbar machen
* Research Suggestions anbinden (= Quellen zu diesem Ort anzeigen)
* GOV anbinden? (= Änderungen in der GOV-Hierarchie anzeigen)
* weitere Wünsche umsetzen?

**Comment by wp4711** [comment]
OK, vielen Dank!
Ich werde, sobald ich eine lauffähige 2.1er version habe, berichten!

**Comment by wp4711** [comment]
Hallo, ich habe es jetzt endlich testen können. Das feature ist - zumindest für mich - fantastisch. Endlich habe ich so die Möglichkeit, die gesamte Geschichte eines Ortes / Hofes etc. abzubilden. DIe Einbindung von Geburts - und Sterbedaten wären noch interessant. Danke für die großartige Arbeit!

**Comment by ric2016** [comment]
Danke für die Rückmeldung - Geburts- und Sterbedaten können über die Moduleinstellungen hinzugefügt werden (seit dem letzten Release).

**Comment by wp4711** [comment]
Danke, habe es gerade getestet. Es funktioniert auch soweit. Das einzige, das mir auffällt, ist ein Problem bei der Sortierung:
Habe ich zb. einen Besitz von 1788-1819 (FROM 1788 TO 1819) und eine Geburt 1790, dann wird die Geburt vor dem Besitz angezeigt, obwohl das Ereignis "Besitz" ja schon 1788 begonnen hat. 
Kann man das ändern?

**Comment by ric2016** [comment]
Ich prüfe das, das scheint nicht sinnvoll so.

**Comment by ric2016** [comment]
Sortierung ist angepaßt [im Code](https://github.com/vesta-webtrees-2-custom-modules/vesta_common/commit/d4ffdac729131c81009133e518d31ca2d110a809), nächstes Release kommt demnächst.

**Comment by wp4711** [comment]
Danke!

**Comment by ric2016** [comment]
Fully supported (now including GOV hierarchies) in latest release (2.1.1.0.0).
