### ISSUE TITLE
Question - Using Vesta Shared Places vs webtrees "Geographic data"

### ISSUE THREAD

**Issue by Norwegian-Sardines** [vesta-webtrees-2-custom-modules/vesta_shared_places#109]
I've created a test server with PHP 7.4, webtrees 2.0.21 and Vesta 2.0.19.2.0 

I've added to this server a GEDCOM with just PLAC tags (no _LOC tags).
I've added to this server a .csv containing nearly all of the places found in the PLAC tags of the installed GEDCOM.

I've set the following Vesta modules to active: Location Data Provider, Shared Places, Places and Pedigree Map, Families, Facts and Events, Common, Clipping Chart

I've ordered the Location Data Provider: Shared Places, webtrees.  With GOV turned off

In the Vesta Shared Places module I've turned on: Displayed title, Shared place structure, Linking of shared places to places

My hopes are:

1) Generate all "Shared Places" from the installed *.csv containing all LONG/LATI for PLAC tags
2) Use the current PLAC tags for "shared places" lookup so that: 
      a) maps will work showing pinned locations, 
      b) eventually adding text to the "shared places" to describe the location.
3) No additional 2 _LOC @xxxx@ tags added to the GEDCOM or GOV look ups.

Can this be done?  What Fix do I run to generate the "Shared Places" records?

**Comment by ric2016** [comment]
The available data fixes do not support the last requirement (3.). I don't really recommend (any longer) to use the option 'Additionally link shared places via name' - Why don't you want the _LOC XRefs?

If this is a one-time operation, I guess you could run the data fix ("Create all missing shared places, and add missing XREFs") and manually merge the created top-level _LOC records from the resulting GEDCOM file into the original GEDCOM file. Or I could create another data fix, but the choice of available fixes may already be too confusing as it is.

**Comment by Norwegian-Sardines** [comment]
I was trying to be as GEDCOM compliant as I could so the _LOC tags would violate that.  

However...   I'm open to the data fix you recommend.  
YES the current list of fixes is rather confusing as they are, so don't add more.

Question - Will the recommended fix add Location_Records only if their is a corresponding PLAC tag -or- will all records found in the "webtrees Geographic Data".  I.E.  does the GEDCOM FACT.PLAC tag drive the addition of shared places or does the *.csv installed Geographic Data drive the process?

**Comment by ric2016** [comment]
> Will the recommended fix add Location_Records only if their is a corresponding PLAC tag

Yes (hopefully). The additional .csv-based data is only used to enhance existing places.

> I was trying to be as GEDCOM compliant as I could so the _LOC tags would violate that.

I wouldn't worry too much about that, you'll have non-standard 0 _LOC records anyway. Any application that is able to handle (or at least ignore) those should be able to deal with the 2 _LOC XRefs as well.
