### ISSUE TITLE
Error: <opening a person's record with shared places

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_shared_places#112]
I get an error message when I open the record of a person with a shared place (including GOV data) in one of the events. The error appears only in the role of a visitor. If I am logged in as a member, the error does not appear.
When I roll back the log, the error occurs the first time at 1st of March.

assert(): RuntimeException in …/app/Services/TreeService.php:137 Stack trace: <b>#0 …/modules_v4/vesta_shared_places/patchedWebtrees/Services/SearchServiceExt.php(201): Fisharebest\Webtrees\Services\TreeService-&amp;gt;find(19)</b> <b>#1 …/modules_v4/vesta_shared_places/patchedWebtrees/Services/SearchServiceExt.php(222): Cissee\WebtreesExt\Services\SearchServiceExt-&amp;gt;Cissee\WebtreesExt\Services\{closure}(Object(stdClass))</b> <b>#2 …/modules_v4/vesta_shared_places/patchedWebtrees/Services/SearchServiceExt.php(147): Cissee\WebtreesExt\Services\SearchServiceExt-&amp;gt;paginateQuery(Object(Illuminate\Database\Query\Builder), Object(Closure), Object(Closure), 0, 9223372036854775806)</b> <b>#3 …/modules_v4/vesta_shared_places/SharedPlacesModule.php(594): Cissee\WebtreesExt\Services\SearchServiceExt-&amp;gt;searchLocationsEOL(Array, Array)</b> <b>#4 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(373): Cissee\Webtrees\Module\SharedPlaces\SharedPlacesModule-&amp;gt;gov2loc(Object(Vesta\Model\GovReference), Object(Fisharebest\Webtrees\Tree))</b> vesta-webtrees-2-custom-modules/vesta_gov4webtrees#5 …/app/Cache.php(59): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::Vesta\Hook\HookInterfaces\{closure}() vesta-webtrees-2-custom-modules/vesta_personal_facts#3 …/vendor/symfony/cache/Adapter/ArrayAdapter.php(63): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true) vesta-webtrees-2-custom-modules/vesta_gov4webtrees#7 …/app/Cache.php(60): Symfony\Component\Cache\Adapter\ArrayAdapter-&amp;gt;get(&#039;4e0c4f84976801b...&#039;, Object(Closure)) <b>#8 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(387): Fisharebest\Webtrees\Cache-&amp;gt;remember(&#039;Vesta\\Hook\\Hook...&#039;, Object(Closure))</b> <b>#9 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(419): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::gov2plac(Object(Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule), Object(Vesta\Model\GovReference), Object(Fisharebest\Webtrees\Tree))</b> <b>#10 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsService.php(132): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::placPplac(Object(Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule), Object(Vesta\Model\PlaceStructure), Object(Illuminate\Support\Collection))</b> <b>#11 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsService.php(229): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsService-&amp;gt;resolvePlace(Object(Vesta\Model\PlaceStructure), Array)</b> <b>#12 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(167): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsService-&amp;gt;getAdditionalFacts(Object(Cissee\WebtreesExt\IndividualExt), true)</b> <b>#13

**Comment by ric2016** [comment]
Fixed in latest release 2.0.23+2.1.0-beta.2.0.0.
