### ISSUE TITLE
Events in _LOC record are not shown in new tab "Place history" 

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#119]
There is an event in my _LOC record:
```
1 EVEN Überfall durch Graf xxx
2 TYPE Brand
2 DATE 1340
```
This event is not shown in the "Place history". Other events, for example from INDI records, are shown in the history.

**Comment by ric2016** [comment]
The events to be shown here are configurable in the module settings in the control panel.
This is currently restricted to selected types though (one reason for this is the I18N of the respective checkboxes).

In any case, this feature is primarily intended for 'indirect' facts & events (i.e. not those on the _LOC itself, but those on INDI/FAM ocuring at the place). I think I wasn't even aware of the possibility to use EVEN on _LOC itself. I guess if you have them, it makes sense to display them in the place history as well, maybe under a separate toggle checkbox.

**Comment by hartenthaler** [comment]
A separate toggle checkbox would be perfect.
Maybe: "location events" or "place events"?

**Comment by ric2016** [comment]
I'm not sure whether it is a good idea at all to allow EVEN on _LOC.

The GEDCOM-L spec defines the subtags via 'regular' EVENT_DETAIL, so you can have a PLAC on this event that is different from the _LOC itself - How is that to be interpreted?

Should such an event show up in the place history of the _LOC (may be confusing) and/or in the place history of the other PLAC?

**Comment by hartenthaler** [comment]
This is a very good point! The GEDCOM Addendum is not clear at that point. Maybe it should be "EVENT_DETAIL" without a new PLAC or a new _LOC.

**Comment by ric2016** [comment]
I think I'll ignore any _LOC:EVEN:PLAC for now, this seems to be in line with the discussion in the GEDCOM-L mailing list so far.

**Comment by ric2016** [comment]
Supported in latest release 2.1.4.1.0.

**Comment by hartenthaler** [comment]
Great! Now the events defined for a shared place are shown. Thank you! Now it is possible to add users defined events to the history of a place.
My observations:
- at the moment (2.1.4) it is not possible to add text to the EVEN itself; I think Greg will change this in the next release
- at the moment it is not possible in the user interface to add _LOC at _LOC:EVEN:PLAC:_LOC; but you do not support_LOC:EVEN:PLAC anyways
- it would be nice to support "indirect" events, e.g. to define "Städtepartnerschaft", for example, to define in the history of a shared place an event that happened at another place; in the same way as you are supporting indirect INDI events

**Comment by ric2016** [comment]
> at the moment it is not possible in the user interface to add _LOC at _LOC:EVEN:PLAC:_LOC

This is missing [here](https://github.com/fisharebest/webtrees/blob/81aa9d168e84a93cdd1208f7500841e1a664caaa/app/Gedcom.php#L1103). I don't consider it to be very important - As we have discussed, the entire PLAC under _LOC is dubious.

> define in the history of a shared place an event that happened at another place

See above, also I doubt this would a feature used by many users.

Perhaps more useful: We could use _LOC events as more specific 'historic events', i.e. display them as additional facts for individuals with events at the same _LOC during the same time. I'm not a big fan of the historic events in general though, so I may end up not supporting this either. Anyway it should be discussed further elsewhere.
