### ISSUE TITLE
Shared Places: Link "View Shared places hierarchy" not active

### ISSUE THREAD

**Issue by ungeahnt** [vesta-webtrees-2-custom-modules/vesta_shared_places#124]
Via modul-settings I've made visible the "Shared places hierarchy" for visitors.

When I logged out it's possible to open the hierarchy via 'Lists'->'Place hierarchy'. It is as expected.

But when I open the hierarchy via 'Lists'->'Shared places', then I see only the message "Enable the Vesta Places and Pedigree map module to view the shared places hierarchy."

![grafik](https://user-images.githubusercontent.com/28572767/169902041-40d886dc-59cc-48c3-b738-cf69ce1e5f1c.png)

Shouldn't it also be possible to switch from 'shared places' to hierarchy?

see here:
https://proavitus.de/tree/proavitus/vesta-place-list
https://proavitus.de/tree/proavitus/shared-place-list

**Comment by ric2016** [comment]
Fixed in code (not released yet).
If you want to test this directly, replace SharedPlacesModule.php with the latest version.

Additional change:
The message "Enable the module ..." is now only shown to admins, it makes no sense to show it to regular users, or visitors.

**Comment by ungeahnt** [comment]
> Fixed in code (not released yet).
If you want to test this directly, replace SharedPlacesModule.php with the latest version.

I've tested it and now this works. Thanks!  

One question: On page 'Place hierarchy', when I click 'reset this filter' and then 'exclude shared places', then the places list shows only one 'unknown' element. How can I check that I've only shared places?

**Comment by ric2016** [comment]
Fix (including second bug i.e. 'unknown' place when there are only shared places) in latest release 2.1.4.1.0.
