### ISSUE TITLE
Layout/Indentation is missing: shared places + notes

### ISSUE THREAD

**Issue by ungeahnt** [vesta-webtrees-2-custom-modules/vesta_shared_places#129]
The unfolded text + note in the red rectangle belongs to 'Shared place data' and should be indented. Like the text from the source below (green rectangle).

![grafik](https://user-images.githubusercontent.com/28572767/174907037-b97859dd-83db-4b33-9cb6-8100da72e77b.png)

**Comment by ric2016** [comment]
This block uses the 'indent' class, which doesn't seem to be up-to-date (not for all themes anyway).
Fixed in code (not released yet).

**Comment by ungeahnt** [comment]
Ah! I have only tested it with Justlight. With the wt theme the indentation works; with FAB not really.
