### ISSUE TITLE
Fatal error - V 2.1.6.1.0

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_shared_places#131]
Fatal error when adding a son or a daughter to a family

![image](https://user-images.githubusercontent.com/13770346/179696231-2bc5d2f0-3d23-4fce-927c-21646891bcdd.png)

**Comment by ric2016** [comment]
File 'GedcomEditServiceExt' is obsolete in Shared Places and was accidentally included in release.
Error occurs due to new file with same name and namespace from 'Classic Look & Feel'.

Workaround: Delete "webtrees\modules_v4\vesta_shared_places\patchedWebtrees\Services\GedcomEditServiceExt.php".

**Comment by ric2016** [comment]
Fixed in latest release 2.1.6.1.1 (also renamed file in 'Classic Look & Feel'; safer in case obsolete files are kept in module folders when overwriting with new release)
