### ISSUE TITLE
Red label/tag "_LOC:EVEN:AGE" shown if opening a shared place with "Edit"

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#137]
Hello Richard,

in webtrees 2.1.7 / vesta 2.1.7.1.0, I observed the following issue:

If opening a shared place with "Edit", a red label/tag "_LOC:EVEN:AGE" is shown in the list of editable tags/data.

Grüße

Markus

![Edit](https://user-images.githubusercontent.com/81484983/200105082-faecccb3-c4e7-4a56-ab1a-3c113f4bb1b2.JPG)

![_LOC-EVEN-AGE](https://user-images.githubusercontent.com/81484983/200105084-d60d348b-f129-4058-88bd-150b9c116984.JPG)

**Comment by ric2016** [comment]
Thanks - Fixed in code, next Vesta release to follow this weekend.
