### ISSUE TITLE
GOV-Kennung is limited to 12 characters

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#138]
Hallo Richard,

while using vesta 2.1.7.1.1, I observed that the "GOV-Kennung" seems to be limited to 12 characters. Therefore, it is not possible to enter certain values, e.g. object_276612 (California).

In the Addendum R2 specification, I found the following:
<GOV_IDENTIFIER> := {Size=1:14}

Grüße

Markus

**Comment by ric2016** [comment]
I cannot reproduce this - Where exactly is the length problematic?
(I think the length was actually restricted in earlier Vesta versions, but that is no longer the case)

**Comment by ric2016** [comment]
Actually, this occurs when using Vesta Shared Places with Vesta Gov4Webtrees disabled:
In this case, the standard webtrees edit control is used which has this restriction, see here: <https://github.com/fisharebest/webtrees/blob/879b2a9ec50b4c13db62ba9b8fc2968bc73b6480/app/Elements/GovIdentifier.php#L34>
So, this is a webtrees bug.

In any case I suggest to enable the Gov4Webtrees module, which solves this and provides a better edit control anyway (and of course other GOV-related functionality)

**Comment by Jefferson49** [comment]
O.k., I understand. I think I have switched off Gov4Webtrees long times ago. After activating Gov4Webtrees, the number of characters is not limited any more. This works!

Thank You for clarifying!

I will file an issue for the webtrees bug as well.

**Comment by Jefferson49** [comment]
created webtrees issue:
https://github.com/fisharebest/webtrees/issues/4601
