### ISSUE TITLE
dutch translation missing

### ISSUE THREAD

**Issue by LarsRabe** [vesta-webtrees-2-custom-modules/vesta_shared_places#143]
for `next lower-level shared places` the dutch translation is not showing although in nl.po the translation is there.
![translation](https://user-images.githubusercontent.com/119816325/211199840-8f9fbb2e-e942-42de-8aee-e80ae41e3e22.jpg)

**Comment by ric2016** [comment]
Not sure how this happened (via weblate), anyway fixed in latest Vesta release 2.1.15.0.3.
