### ISSUE TITLE
Adding a new shared place is not possible in the modal after creating an unlinked new person in the Control Panel

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#144]
Observed with vesta 2.1.15.0.3 and webtrees 2.1.15

After creating an unlinked new person in the Control Panel, it is not possible to create a new shared place in the pop-up modal, see screenshot.

![New shared place for new unlinked individual](https://user-images.githubusercontent.com/81484983/212531624-544d0fb7-57da-415b-9552-cab2791d82b8.JPG)

**Comment by ric2016** [comment]
This is an issue in other views as well, at least in:
`Add a son | Add a daughter | Add a child` etc. (basically everywhere a new individual. is created)

Also for MARR:PLAC:_LOC e.g. in
`Add a wife using an existing individual`

Impl note:
Cause is the missing 'special' modal, cf [other views](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/blob/fa72151e288fca77f08f5c254d63c5eb75f27d80/resources/views/edit/edit-fact.phtml#L19)
Is there a better way to handle this?

**Comment by ric2016** [comment]
Fixed in Vesta release 2.1.16.0.0.

**Comment by Jefferson49** [comment]
Thank you very much! I already tested the latest version successfully
