### ISSUE TITLE
Gedcom 7 language tags

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#149]
With a first Gedcom 7 version of my data, I checked how it works in webtrees. Overall, webtrees and vesta look very good and seem to work with Gedcom 7. (The only major issue identfiyed is @ VOID@ pointers [#4695](https://github.com/fisharebest/webtrees/issues/4695), which is not the point of this issue here.)

Since Gedcom 7 changed the languages into [iana tags](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), the languages do not translate in the same way like before. Vesta shows the language tags instead. 

On the roadmap to Gedcom 7, it would be nice to support the language tags. However, not urgent for me at the moment.

Grüße

Markus

![_LOC Sprache](https://user-images.githubusercontent.com/81484983/218318257-60c0f96a-7132-4cc9-92ad-e578059856a7.JPG)

**Comment by ric2016** [comment]
It's not clear to me what the roadmap of webtrees re: GEDCOM 7 is for cases like this:
It's rather straightforward to display these tags properly, but should the editing be based on the GEDCOM version of the respective tree? Do you know whether there are any other areas where webtrees already stores GEDCOM-7-specific structures or contents?

**Comment by Jefferson49** [comment]
My understanding is that webtrees currently only intends to display Gedcom 7. There seems to be no clear roadmap for editing Gedcom 7. I remember some discussions in the forum about allowing parallel Gedcom 5.5.1 and 7.0 editing. However, Greg seems to have doubts if this is possible. Regarding editing, some compatibility issues are already addressed (e.g. upper case values like GERMAN or MARRIED), but they also created problems with existing tools. Other editing preparations for Gedcom 7, I have not recognized yet.

For myself, I want to be prepared. I wrote a simple Gedcom 7 converter in one of my custom modules and started testing Gedcom 7 with the relevant tool set I am using. Until now, it looks better than expected and most of the things I use are working.

Related to the language tags, I would propose to enable displaying the related languages as a first step. If preparing the iana tag tables etc, editing could already be prepared. However, editing will depend on further decisions of webtrees.

**Comment by ric2016** [comment]
I'll adjust this for display as suggested, editing will have to wait.

Note that this will have to be addressed in webtrees as well for HEAD:LANG (not sure if this is displayed anywhere at all currently) and SUBM:LANG (displayed via LIsts > Submitters).

**Comment by ric2016** [comment]
Fixed in latest Vesta release 2.1.16.1.3.

**Comment by Jefferson49** [comment]
Hello Richard, 

thank you very much for inlcuding this feature in the latest release! When testing some examples, it worked very fine.

I identified the following topic, where I do not know what should be the correct behavior:
If using the language tag "sh", it is not translated.

![LANG sh](https://user-images.githubusercontent.com/81484983/220032673-efc5b1e6-0c22-44c0-a82c-145e1fb683ed.JPG)

In the iana language file, I found the following:

```
Type: language
Subtag: sh
Description: Serbo-Croatian
Added: 2005-10-16
Scope: macrolanguage
Comments: sr, hr, bs are preferred for most modern uses
```

Based on this hint, I will change "sh" in "sr" in my database, because my data is from Serbia (and not Croatia, Bosnia). Therefore, the issue will not show up in my data again. 

However, in general, I do not know what is the right approach:
+ Should "macrolanguages" be excluded from the list of languages?
+ In the Gedcom 7.0.11 specification, I found: "where language subtags are registered by the IANA". In the iana file, "sh" is a subtag.
+ In Gedom 5.5.1, I found: "Serb" and "Serbo_Croa", which could be converted to "sr" and "sh"

**Comment by Jefferson49** [comment]
In the edit view, language tags are currently shown as upper case:

![LANG upper case](https://user-images.githubusercontent.com/81484983/220037353-a4747162-e715-4e5e-b4c0-120fdf1642b7.JPG)

As we already discussed, the roadmap to Gedcom 7 editing is not clear. Therefore, I do not know if it makes sense to discuss it at the moment. I guess that in future editing, the language tags will not be visible anyway, because the language names can be selected.

**Comment by ric2016** [comment]
webtrees currently only supports a subset of languages, [see here](https://github.com/fisharebest/webtrees/blob/main/app/Elements/LanguageId.php). This will probably have to be extended. Proper internationalization will have to be added as well.

Editing support will have to wait until webtrees decides how to handle the switch to GEEDCOM 7.
