### ISSUE TITLE
If entering birth place and death place in parallel (e.g. for a new individual), the death place overwrites the birth place

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#151]
Oberved with vesta vesta 2.1.16.1.4

If creating a new individual and using the editing mask for all events/facts, vesta seems to mix the birth and death places. In the provides screenshot, "Dachau" (entered as death place) is taken as PLAC text for the birth place and the PLAC text for the death place stays empty. The original PLAC text "Nünchritz" for birth is overwritten.

While entering shared places in the last days, I have the impression that it also happens in other cases that the _LOC tag is filled, but the PLAC tag stays empty.

![vesta Geburts- und Sterbeort](https://user-images.githubusercontent.com/81484983/221405279-9800d5cb-f663-4225-b246-ef23737718c7.JPG)

**Comment by ric2016** [comment]
I can reproduce this - the functionality assumes there is only one PLAC in the dialog, i.e. this was always broken for multi-fact dialogs. Will be fixed in next release.

**Comment by ric2016** [comment]
Fixed in Release 2.1.16.1.5.
