### ISSUE TITLE
If adding a shared place to SOUR:DATA:EVEN, the place name is not stored in SOUR:DATA:EVEN:PLAC

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#153]
Observed with vesta 2.1.16.1.5 and webtrees 2.1.16

If adding a shared place to SOUR:DATA:EVEN, the shared place is saved in _LOC. However, the place name is not stored in PLAC.

Since I was working continously with SOUR:DATA:_LOC in the last days, and just recently installed vesta 2.1.16.1.5, I assume the behavior is related to the new vesta version.

![vesta SOUR _LOC](https://user-images.githubusercontent.com/81484983/222895793-cc5334a0-124e-4421-8e16-01a09d6914b3.JPG)

**Comment by ric2016** [comment]
Oops, this is a regression introduced by fixing #151.

**Comment by ric2016** [comment]
Hopefully fixed everywhere by last commit.
Vesta Release to follow.
