### ISSUE TITLE
SOUR:DATA:EVEN:PLAC is shown as unknown Gedcom structure

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#161]
Observed with webtrees 2.1.17 and vesta vesta.2.1.17.0.2

If editing the data of a source, SOUR-DATA-EVEN-PLAC is shown as unknown Gedcom structure. I do not know if this is an error in webtrees or in vesta shared places. It seems to be new in 2.1.17, because I did not observe this before.

![SOUR-DATA-EVEN-PLAC](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/assets/81484983/59f3f469-acf8-4682-b3d2-4c9d25d326e6)

**Comment by ric2016** [comment]
Its a webtrees issue (tested with Vesta disabled), the missing tags is actually
SOUR:DATA:EVEN:PLAC:_GOV

<img width="196" alt="missing" src="https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/assets/18174787/b6cecedd-64ae-4331-8b9a-f40bdfb74f41">

**Comment by ric2016** [comment]
Should be fixed in webtrees:
https://github.com/fisharebest/webtrees/issues/4849
