### ISSUE TITLE
JSON data error in Data fixes for ⚶ Vesta Shared Places

### ISSUE THREAD

**Issue by Manja-S** [vesta-webtrees-2-custom-modules/vesta_shared_places#162]
When I try to run the data fixes:

- Enhance existing shared places with tree-independent data (I clicked Update all, after searching)
- Add missing XREFs  (I clicked Update all, after searching)
- Create missing shared places from tree-independent data, and add missing XREFs  (I clicked Update all, after searching)
- Create all missing shared places, and add missing XREFs   (I clicked Update all, after searching)

I get this message:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Concerns:** Control panel => Manage family trees => Data fixes => ⚶ Vesta Shared Places

**Comment by ric2016** [comment]
I cannot reproduce this. Can you check your browser development tools, Network tab,  for failing requests and post the resprective (non-json) response data here?

**Comment by Manja-S** [comment]
Is this what you are looking for?

---

POST
https://webtrees.schledorn.nl/tree/Schledorn/data-fix
[HTTP/2 302 Found 195ms]

GET
https://webtrees.schledorn.nl/tree/Schledorn/data-fix/_vesta_shared_places_
[HTTP/2 200 OK 368ms]

GET
https://webtrees.schledorn.nl/public/css/vendor.min.css?v=2.1.17
[HTTP/2 304 Not Modified 9ms]

GET
https://webtrees.schledorn.nl/public/css/administration.min.css?v=2.1.17
[HTTP/2 304 Not Modified 10ms]

GET
https://webtrees.schledorn.nl/public/js/vendor.min.js?v=2.1.17
[HTTP/2 304 Not Modified 8ms]

GET
https://webtrees.schledorn.nl/public/js/webtrees.min.js?v=2.1.17
[HTTP/2 304 Not Modified 8ms]

GET
https://webtrees.schledorn.nl/public/favicon.ico?v=2.1.17
[HTTP/2 200 OK 0ms]

XHRPOST
https://webtrees.schledorn.nl/tree/Schledorn/data-fix/_vesta_shared_places_/update-all?mode=enhance&data-fix-table_length=10
[HTTP/2 501 Not Implemented 10ms]

---

**Comment by Manja-S** [comment]
So I think I'd have to contact my hosting provider. Thank you for helping me to identify the problem, so I know how to tell them about it.
