### ISSUE TITLE
Websites error logs: Target class [Cissee\WebtreesExt\Http\RequestHandlers\AutoCompletePlaceExt] does not exist.

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_shared_places#169]
In the website error logs on my public internet server, I found the following error.

Target class [Cissee\WebtreesExt\Http\RequestHandlers\AutoCompletePlaceExt] does not exist. …/vendor/illuminate/container/Container.php:879 #0 …/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container-&gt;build(&#039;Cissee\\Webtrees...&#039;) #1

The error is logged several times between 2023-11-15 17:25:00 and 2023-11-15 17:25:58. The website logs show that I was logged in as administrator during this time. However, I do not remember what I was exactly doing on Nov 15th. I guess I updated to webtrees 2.1.18 and the latest vesta release. However, not sure.

Full stack trace as attachement.
[2023-11-15_shared_places_error_in_website_logs.txt](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/files/13470268/2023-11-15_shared_places_error_in_website_logs.txt)

**Comment by ric2016** [comment]
AutoCompletePlaceExt.php was introduced in release 2.1.18.0.1. If the error isn't reproducible (for me it is not), no further action is required.
