### ISSUE TITLE
Minor display fix - remove space

### ISSUE THREAD

**Issue by HerzScheisse** [vesta-webtrees-2-custom-modules/vesta_shared_places#170]
Hey ric,

Dont know which module creates this, i tried to locate this, but can't find it... so i'll post it here, in hope that its the right module...

Currently i make more and more use of the shared places feature... and there is one thing that bothers me a bit...
Is it possible to remove this space between GOV and Data of the shared place?

![2024-02-23 02_22_48-Bertha Ursula Hoffmann 1946– – Familienforschung eisold family - Brave](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/assets/146635896/3e99dbee-ddfa-4514-b026-ac86e3f4a921)

Thanks
Holger

**Comment by ric2016** [comment]
I had to track this down as well. [SharedPlacesModule.factPlaceAdditionsAfterNotes is responsible for this](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/blob/2be2d1869827e942668a17736471f16df6ca0db4/SharedPlacesModule.php#L977). I'll change it to something that can be handled via css.

**Comment by ric2016** [comment]
Now styled via css.

Use something like

```
div.vesta_sp_data {
    margin-top: 0em !important;
}
```

in the css module to overrride.

**Comment by HerzScheisse** [comment]
Thank you!

**Comment by HerzScheisse** [comment]
hey ric, sorry for posting in this already closed issue, but it may be not needed to open a new one... hope this is okay...

related to the above issue... do you have a suggestion to "unbold" the "Daten des gemeinsamen Ortes" ?

I tried to play with `font-weight: normal !important;` in webtrees.css within the shared_places module and also in the Control Panel CSS module... but dont have had any changes...

it would be great if you have a solution to fix this... imho this line dont need to be in bold

Thanks

**Comment by ric2016** [comment]
In general it's better to open a separate issue.
The relevant element has `<span class="label">`, just like other elements such as Source and Note. I'm reluctant to change this.

You could style `.label` in general, or just under the newly introduced `div.vesta_sp_data`, like this:

```
div.vesta_sp_data span.label {
    font-weight: normal !important;
}
```

**Comment by HerzScheisse** [comment]
awsome... dont know what i did wrong... maybe a cache issue... but now it works... thanks again :)
