### ISSUE TITLE
Frage Eingabe

### ISSUE THREAD

**Issue by wp4711** [vesta-webtrees-2-custom-modules/vesta_shared_places#173]
hallo, Ich habe eine Frage: Wenn ich eine neue Gedcom habe. Wie genau müssen die Orte aussehen, damit die bei der datenkorrektur richtig aufgeteilt werden? müssen doie immer gleich sein?
Z.b: Altwaldhäusl 27, Münichreith, Niederösterreich, Österreich
Wird nicht getrennt. Es gibt aber genug Orte, wo auch ohne Beistrich Trennung Bzw. eventuell kürzer getrennt wurde.

Danke!!!
lg walter aus Niederösterreich

**Comment by ric2016** [comment]
Ich verstehe die Frage nicht - Um welche Datenkorrektur geht es?
Enthält die GEDCOM-Datei bereits _LOC-Records, oder sollen diese über die Datenkorrektur erstellt werden?

Wie sieht ein Beispiel aus, wo es wie erwartet funktioniert hat bzw. was ist das Ergebnis?

**Comment by wp4711** [comment]
Hallo!

Ich versuche es zu erklären:

Ich habe die Orte einer Gedcom datei im Format:

Altwaldhäusl 36, Münichreith, Niederösterreich, Österreich
oder 
Arndorf 11, Arndorf, Niederösterreich, Österreich
oder 
Münichreith 18, Münichreith, Niederösterreich, Österreich
aber auch nur zb:
Braunau

Ich will die Datei nun im WT importieren, und mit der Korrektur Gemeinsame Orte hierarchisieren die Orte so haben, dass alle Häuser (also die Ortsnamen mit Hausnummern) hirachisch unter dem Ort stehen.

Nun habe ich folgendes Problem:
Bei Münichreith 19 funktioniert es, er schlägt folgende Korrektur vor:

Vorschau — Münichreith 19, Münichreith, Niederösterreich, Österreich

0 @L101@ _LOC
1 NAME Münichreith 19, Münichreith, Niederösterreich, Österreich
1 NAME Münichreith 19
1 NOTE Kramerhaus
1 _LOC @NX_Jg6jHAoDXEEN25au@
2 TYPE POLI
0 @NX_Jg6jHAoDXEEN25au@ _LOC
1 NAME Münichreith
1 _LOC @NX_L5797RNihWqvF2mg@
2 TYPE POLI
0 @NX_L5797RNihWqvF2mg@ _LOC
1 NAME Niederösterreich
1 _LOC @NX_5jzWW9DRnbI2O2Iy@
2 TYPE POLI
0 @NX_5jzWW9DRnbI2O2Iy@ _LOC
1 NAME Österreich

Bei Münichreith 18, welches genau gleich formatiert ist, funktioniert es, wie bei vielen anderen, nicht.
![Screenshot 2024-03-19 141925](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/assets/96334271/774d09c4-cf66-4d8b-88d5-16abca4d12d5)

**Comment by ric2016** [comment]
Ja, das sieht seltsam aus. 
Als ob es "pro führender Ziffer der Hausnummmer" nur 1x möglich ist ...

Wenn man die Liste weiter durchgeht, setzt sich dieses Muster so fort?

**Comment by ric2016** [comment]
Ich kann das leider nicht reproduzieren.

Ich kann anbieten, das Problem anhand Ihrer GEDCOM-Datei zu analysieren. Diese kann natürlich auch gekürzt sein, es geht ja nur um die _LOC-Datensätze. Gerne per Email, also nicht unbedingt hier öffentlich anhängen.

(Ich werde die Datei in jedem Fall nur zur Analyse des Problems verwenden)
