### ISSUE TITLE
missing icon in latest changes block on tree home

### ISSUE THREAD

**Issue by HerzScheisse** [vesta-webtrees-2-custom-modules/vesta_shared_places#176]
Hi,

testetd with wt-version 2.1.18 & 2.1.19, F.A.B & webtrees theme

if we edit a shared place, it will be displayed in the "latest changes" block on the tree home... but this entry is missing a icon...

![shared place missing icon](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/assets/146635896/d61c0c54-9ab4-47f8-9547-ce9a03a089d8)

If we have a media object linked to the shared place, and look for that image in the medialist, there we have a shared place location icon..
Maybe reuse that...
![shared place icon](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/assets/146635896/6b29d0e9-093d-4e87-afbd-1de0c347d078)

**Comment by ric2016** [comment]
Webtrees elsewhere has rudimentary support for the Location type (including the icon shown in the screenshot, while Vesta uses the globe image for Shared Places - this should probably be aligned better), but not in this module.

This will have to be adjusted [here](https://github.com/fisharebest/webtrees/blob/a473b260f09939b01eed3ab6d4bd57a616d382a2/resources/views/modules/recent_changes/changes-table.phtml#L59), similar code including Location [is here](https://github.com/fisharebest/webtrees/blob/a473b260f09939b01eed3ab6d4bd57a616d382a2/resources/views/icons/record.phtml#L33).

**Comment by HerzScheisse** [comment]
thanks ric, yeah that makes sense... 

great you took the time to find the right place... I added these changes and tested it... it works... will provide a PR to wt... Thanks
