### ISSUE TITLE
Type of location

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#18]
"Type of Location" is labeled as "Type of hierarchical relationship". This is wrong.
![Screenshot (11)_LI](https://user-images.githubusercontent.com/6324175/88116448-df5c2380-cbb8-11ea-8f2e-2112d9a3a708.jpg)

It is very good that this module now supports hierarchical locations. I just converted all my location records, but now I have several records with the same name on different hierarchical levels (e.g. as Stadt and Landkreis). In the list of all shared places, it is now not any longer possible to distinguish them. Even the tooltip does not help. So I suggest to use the "type of location" as an additional element, maybe in a second column in the table of the list of shared places.

**Comment by ric2016** [comment]
I see - "Type of Location" isn't really supported yet, I'll add that next.
(only the TYPE tag for hierarchical relations is explicitly supported at the moment)

The list of shared places has a column (new in 2.0.6.2.1) showing the full hierarchy, this should help to distinguish records with the same name. But it's easy to add another column with the type of location, as suggsted.

**Comment by ric2016** [comment]
'Type of location' is supported now.
When editing, there is a dropdown for _GOVTYPE - not sure how useful that is, given the large number of possible values.

**Comment by ric2016** [comment]
Release 2.0.6.2.3 adds Type of Location to shared places list, as suggested.
