### ISSUE TITLE
Error in place hierachy

### ISSUE THREAD

**Issue by Fa10175** [vesta-webtrees-2-custom-modules/vesta_shared_places#22]
I download last webtrees and vesta module
when i go to
![Sans titre](https://user-images.githubusercontent.com/10681601/88781730-099b7b80-d18d-11ea-81c8-d0b7a2168ce3.jpg)
i have this error
[new 1.pdf](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/files/4993894/new.1.pdf)

i hope that help you

**Comment by Fa10175** [comment]
Solve with 2.0.7.1

**Comment by ric2016** [comment]
Yes, this was fixed yesterday in [vesta-common](https://github.com/vesta-webtrees-2-custom-modules/vesta_common/issues/5).
