### ISSUE TITLE
Ok..  I installed "Shared Places and the Core code.  What next?

### ISSUE THREAD

**Issue by Norwegian-Sardines** [vesta-webtrees-2-custom-modules/vesta_shared_places#23]
So.. I see that I can add a new "Shared Place" and adds all of the levels to the PlaceLocation table and the Places table.  It also updates the Other table with the _LOC records.  This is great! 

Now I also see that the Icon next to the location will take me to the Location Record where I can use my notes (rather than shared notes to tell stuff about a location.  This is also great!!!

It would be great if you had a "fix it" that added selected PLAC tags to the Location Table so I can reuse the hierarchy already built.  I probably don't need all of them at once just select ones.

**Comment by Norwegian-Sardines** [comment]
Oh wait.... I see the "add a shared place" icon.  But when I run it the message says something was added but no _LOC record were added to the Other Table.

**Comment by Norwegian-Sardines** [comment]
Oops, I forgot to accept the changes.  A yellow box with the Accept/Reject did not show up to make the update.  So I forgot to look at the pending changes menu.  My bad!!

**Comment by Norwegian-Sardines** [comment]
Ok.  So I'm playing around with the Notes and we are only allowed on NOTE.  This is probably okay for most people but several of my places currently have two or more depending on the history that is being written.  I may have to rethink all of my history notes.

**Comment by ric2016** [comment]
Thank you for testing!
There are definitely some data fixes missing. E.g. one to transfer data from the placelocation table to shared places, another one to create shared places for existing places and maybe link them directly, and so on. I definitely plan to implement those.

Regarding multiple notes: It is already possible to add multiple notes and shared notes to a shared place. Does this not work for you? You should be able to add unlimited facts of these types.

**Comment by ric2016** [comment]
I'm closing this for now as there don't seem to be any specific issues left here.
