### ISSUE TITLE
error with shared place after update to webtrees 2.0.9

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#32]
When I try to edit a BURI record, which contains a shared place (without a _LOC reference to this shared place), there is an error:
`autocomplete-place …/vendor/aura/router/src/Map.php:152
#0 …/app/Helpers/functions.php(169): Aura\Router\Map->getRoute('autocomplete-pl...')
#1 …/modules_v4/vesta_shared_places/patchedWebtrees/Functions/FunctionsEditLoc.php(413): route('autocomplete-pl...', Array)
#2 …/modules_v4/vesta_shared_places/patchedWebtrees/Functions/ExtendedFunctionsEditPlacHandler.php(54): Cissee\WebtreesExt\Functions\FunctionsEditLoc::addSimpleTagWithGedcomRecord(NULL, Object(Fisharebest\Webtrees\Tree), '2 PLAC Martin-L...', 'INDI', 'Bestattungsort')
#3 …/modules_v4/vesta_shared_places/replacedWebtrees/Functions/FunctionsEdit.php(832): Cissee\WebtreesExt\Functions\ExtendedFunctionsEditPlacHandler::addSimpleTag(Object(Fisharebest\Webtrees\Tree), '2 PLAC Martin-L...', 'INDI', 'Bestattungsort')
#4 …/modules_v4/vesta_shared_places/resources/views/edit/edit-fact.phtml(120): Fisharebest\Webtrees\Functions\FunctionsEdit::createEditForm(Object(Fisharebest\Webtrees\Fact))
#5 …/app/View.php(189): include('/mnt/web312/a3/...')
#6 …/app/View.php(286): Fisharebest\Webtrees\View->render()
#7 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('edit/edit-fact', Array)
#8 …/app/Http/ViewResponseTrait.php(51): view('edit/edit-fact', Array)
#9 …/app/Http/RequestHandlers/EditFactPage.php(80): Fisharebest\Webtrees\Http\RequestHandlers\EditFactPage->viewResponse('edit/edit-fact', Array)
#10 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\EditFactPage->handle(Object(Nyholm\Psr7\ServerRequest))
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#12 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(151): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#14 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(212): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …/app/Http/Middleware/AuthEditor.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthEditor->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))`

**Comment by hartenthaler** [comment]
This error occurs when I try to edit any type of record for any INDI or FAM with or without a place. Even when I disable the module, the error is still there:
`autocomplete-place …/vendor/aura/router/src/Map.php:152
#0 …/app/Helpers/functions.php(169): Aura\Router\Map->getRoute('autocomplete-pl...')
#1 …/modules_v4/vesta_shared_places.disable/replacedWebtrees/Functions/FunctionsEdit.php(502): route('autocomplete-pl...', Array)
#2 …/modules_v4/vesta_shared_places.disable/patchedWebtrees/Functions/FunctionsEditPlacHandler.php(43): Fisharebest\Webtrees\Functions\FunctionsEdit::addSimpleTag(Object(Fisharebest\Webtrees\Tree), '2 PLAC Martin-L...', 'INDI', 'Bestattungsort')
#3 …/modules_v4/vesta_shared_places.disable/replacedWebtrees/Functions/FunctionsEdit.php(832): Cissee\WebtreesExt\Functions\FunctionsEditPlacHandler::addSimpleTag(Object(Fisharebest\Webtrees\Tree), '2 PLAC Martin-L...', 'INDI', 'Bestattungsort')
#4 …/resources/views/edit/edit-fact.phtml(29): Fisharebest\Webtrees\Functions\FunctionsEdit::createEditForm(Object(Fisharebest\Webtrees\Fact))
#5 …/app/View.php(189): include('/mnt/web312/a3/...')
#6 …/app/View.php(286): Fisharebest\Webtrees\View->render()`

**Comment by hartenthaler** [comment]
deleting the modules vesta_research_suggestions and vesta_shared_places "solved" the problem

**Comment by ric2016** [comment]
> Even when I disable the module, the error is still there:

This is due to autoloading and replacement of some webtrees core classes (required due to a lack of extensibility of the core code in some places), which occurs even when the module is disabled. I may be able to improve this, anyway hopefully these kinds of replacements won't be required in webtrees 2.1.x anymore.

It's also unfortunate that currently each webtrees upgrade changes core functionality in a manner that breaks custom modules. I hope this stops eventually, otherwise we'll have to introduce a check for compatibility with custom modules when upgrading webtrees.

Good news is that the actual issue is easy to fix, next Vesta release will follow today.

**Comment by ric2016** [comment]
Fixed in latest release.
