### ISSUE TITLE
superfluous characters when generating common place

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#36]
Sometimes when generetaing a common place, there is a confirmation message like
`Der Gemeinsame Ort Schloss Hinnenburg wurde erstellt.
Schloss Hinnenburg 3 Test2`
"3 Test2" is irritating.

**Comment by ric2016** [comment]
Caused by a broken (test) translation in weblate for German, which I later forgot to fix:
https://hosted.weblate.org/translate/vesta-webtrees-custom-modules/vesta-shared-places/de/?offset=1&q=Test2&sort_by=-priority%2Cposition&checksum=

I'll adjust this.

**Comment by ric2016** [comment]
Fixed in latest release.
