### ISSUE TITLE
Undefined Method: Filter::escapeHTML in SharedPlacedModule.php

### ISSUE THREAD

**Issue by terrymgray** [vesta-webtrees-2-custom-modules/vesta_shared_places#5]
PHP error: Call to undefined method Fisharebest\Webtrees\Filter::escapeHtml() …\modules_v4\vesta_shared_places\SharedPlacesModule.php:258

I have both the custom Vesta 'Facts and Events' and 'Shared Places' modules installed. Issue arises when Shared Places Module is enabled and Preferences tick-box is set to 'Restrict to Specific Facts and Events' - see screenshort. 
NB: the issue is not seen if the tick-box is deselected.  

[error.log](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/files/3591679/error.log)

![preferences](https://user-images.githubusercontent.com/1483340/64550371-b927ef00-d32a-11e9-8ee2-96942a7219e6.PNG)

Running webtrees 2 (beta 4)

Side Note: May be useful to prevent user from selecting 'Specific facts and events' tick-box where no Gedcom fact types are selected as this causes a PHP error

**Comment by ric2016** [comment]
Thank you for the detailed report - I could reproduce and fix both bugs easily. Release to follow.
