### ISSUE TITLE
webtrees Geographic data after creating shared places

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_shared_places#56]
webtrees 2.0.11, vesta modules 2.0.11.2.1
I created shared places in a tree using Data fix > Create missing shared places from tree-independent data, and add missing XREFs.
After clicking 'Update all' all hierarchy of shared places was created with correct coordinates taken from Geographic data. But the list of places in Geographic data changed!

**The list before Data fix:**
![image](https://user-images.githubusercontent.com/350656/109384620-6a8b5d80-78ee-11eb-8ddb-30088dd7c24a.png)

**The list after Data fix:**
![image](https://user-images.githubusercontent.com/350656/109384657-a6262780-78ee-11eb-8bfb-5facd9533e9c.png)

**My question is: Is this an intended result?**

**Comment by ric2016** [comment]
No, this seems dubious.

Do the newly created shared places have proper hierarchiers, or do you now e.g. have a top-level shared place 'Aarau' as well?

In the module configuration, is 'Use hierarchical shared places' checked?

**Comment by ric2016** [comment]
Ok, that's all as it should be.
Do these unexpected top-level entries show up in the place hierarchy as well, or only in geographic data?
I'll try to reproduce this.

**Comment by jpretired** [comment]
These "new" top-level entries show up in geographic data only.
I am not using pending changes, they are accepted automatically.

**Comment by ric2016** [comment]
Thanks for the feedback.
So far, I identified a likely related issue #57 - I'll fix this first and see if that helps.

**Comment by ric2016** [comment]
Thanks for the feedback.
So far, I identified a likely related issue #57 - I'll fix this first and see if that helps.

**Comment by ric2016** [comment]
I have fixed the underlying issue in #57 (hopefully this was actually the cause).

I guess it would be tricky for you to test this again. Anyway it shouldn't occur again. I'm afraid you'll have to clean up the 'geographic data' manually (or delete rows without coordinates directly in the database table, but make sure to backup everything if you do that!).

**Comment by jpretired** [comment]
Richard - no progress. I have tested it like this:
1. Restored geographic data and tree data from GEDCOM to the state before. i.e. without shared places.
2. Upgraded vesta modules to 2.0.11.3.0.
3. Used 'Data fix > Create missing shared places from tree-independent data, and add missing XREFs' as in my initial post above.
Now the gepgraphic data look again the same like on the screenshot in the initial post.
What more, the shared places are not created correctly, only the highest places have coordinates and have no link to lower levels.
If it helps you I can introduce an admin user for you on my webtrees test site and send its credentials to you by email.
Please let me know.

**Comment by ric2016** [comment]
Uh, that's not good - sorry about that.

> What more, the shared places are not created correctly, only the highest places have coordinates and have no link to lower levels.

So this is worse than before now? Bah.

I think the easiest way for me to test and fix this issue is by using your test GEDCOM on my local system, you can send it to me at <ric@richard-cissee.de>. Of course I'll only use the GEDCOM for testing and delete it afterwards.

**Comment by jpretired** [comment]
I sent 2 files to ric@richard-cissee.de
Josef

**Comment by ric2016** [comment]
I think I fixed the issue now - The cause was that for a place "A, B, C", a check for map coordinates was made using only "A". That lead to the additional entries in "Geographix Data", and also to missing shared places because no coordinates could be found.

By the way, I also found and fixed another issue - This should result in a much faster execution of large data fixes via "Update all".

**Comment by jpretired** [comment]
Thank you for good news. You'll probably create new release of vesta modules?

**Comment by ric2016** [comment]
The new release 2.0.11.3.1 is already available (the new version may not show up yet in your webtrees, but you can download it anyway).

**Comment by jpretired** [comment]
OK, I will try it in the morning with fresh brain and let you know.
Josef

**Comment by jpretired** [comment]
The **issue is fixed** as long as I can say so far - many thanks, Richard!
The geographic data list remains untouched and randomly checked shared places have correct coordinates.

**Comment by ric2016** [comment]
Glad to hear it - Let me know if there are any other other issues. There are so many different use cases for shared places that it is easy to miss something; although this was a rather obvious bug.
