### ISSUE TITLE
Error after click on place name

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_shared_places#60]
wt 2.0.12, vesta 2.0.11.4.0
Individual's death: newly introduced place name.
It is not a shared place yet, it has no coordinates in geographic data yet.
![image](https://user-images.githubusercontent.com/350656/110978874-30956f00-8364-11eb-9052-c09b8965ba35.png)

Clicking on the name produces an error, see attached file:
[20210312-error.txt](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/files/6131983/20210312-error.txt)

**Comment by ric2016** [comment]
I can reproduce this - Will be fixed in the next release (hopefully tomorrow).

**Comment by ric2016** [comment]
Fixed in latest release 2.0.12.0.0.
