### ISSUE TITLE
Error after click on media object name

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_shared_places#62]
webtrees 2.0.12, vesta modules 2.0.12.0.0.
Lists > Media objects > search displays media objects.
After clicking on a media object name - error, see attached file:
[20210313-error.txt](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/files/6135247/20210313-error.txt)

**Comment by jpretired** [comment]
After posting this issue I found a forum post https://www.webtrees.net/index.php/en/forum/help-for-2-0/35503-error-on-managing-media#83861 saying that the issue is fixed.
I tested the latest release and it is really fixed.

**Comment by ric2016** [comment]
Yes, I missed that one in the initial release.
