### ISSUE TITLE
Convert newly introduced place to shared place

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_shared_places#63]
After adding place to an individual's event I edit the event:
By means of + I want to create a shared place:
![image](https://user-images.githubusercontent.com/350656/111044537-7aa45080-8449-11eb-99eb-ec10d82587dc.png)

A form pops up:
![image](https://user-images.githubusercontent.com/350656/111044555-94459800-8449-11eb-91d4-5d989f46ea66.png)

I fll in the name of shared place and click on 'save'. The form stays on with no message, have to cancel it to close.
**But the shared place is created as can be seen afterwards in list of shared places!**

I go on to edit the shared place to add a higher level shared place (which exists):
![image](https://user-images.githubusercontent.com/350656/111044797-feab0800-844a-11eb-9296-f8a4aa1effeb.png)

I try to type the name of higher level shared place but can't - 'The results could not be loaded.'

Please **what is the right way to do this task?**

**Comment by ric2016** [comment]
All of this is cases by newly introduced webtrees functionality for location handling:
"Create a location" is the webtrees form (the shared places module form additionally has support for hierarchies and GOV ids etc)

I'll disable this in case the Shared Places module is active.

**Comment by ric2016** [comment]
Fixed in latest release 2.0.12.0.2.

**Comment by jpretired** [comment]
Richard, now it is perfect and consummate, thank you.
Let me only ask whether these complications will occur with every new release of webtrees?

**Comment by ric2016** [comment]
I hope not! Unfortunately the webtrees releases tend to have a rather large amount of changes - It would be easier if there were smaller releases in between.

In any case I expect that from webtrees 2.1 on the codebase stabilizes.
