### ISSUE TITLE
[request] Collapse Information in Administration

### ISSUE THREAD

**Issue by Gunnar-GO** [vesta-webtrees-2-custom-modules/vesta_shared_places#68]
The use of more than one extension results in doublette informations.

![image](https://user-images.githubusercontent.com/24938625/114002323-0d73b780-985d-11eb-8502-5dfecf2ddca5.png)

an addition of 
```
 .wt-custom-module-info {    margin-top: -20px; padding-top: 20px;  height: 0; overflow: hidden; }
 .wt-custom-module-info:hover {    height: inherit; }
```
would result in:
![image](https://user-images.githubusercontent.com/24938625/114002547-3f851980-985d-11eb-9a1f-e7d60f24c798.png)

with mouse hover over the line would look like this:
![image](https://user-images.githubusercontent.com/24938625/114002648-588dca80-985d-11eb-8c0d-4b899bac0068.png)

may it be an option?

**Comment by ric2016** [comment]
Frankly I don't think this is an important issue.

In any case, you should be able to achieve this via the 'CSS and JS' custom module, or you should suggest it in webtrees itself - This is not something that a Vesta module should decide.
