### ISSUE TITLE
adding additional information: Too much concepts

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#71]
If you like to add more information to a shared place there are three concepts:
1 add from pop up window
2 add predefined items
3 "add media object" as an own menu topic
Maybe it is possible to reduce this to one or two possibilities.
![Screenshot (259)_LI](https://user-images.githubusercontent.com/6324175/115936577-eee50180-a495-11eb-99a3-a2e2fffd028f.jpg)

**Comment by ric2016** [comment]
The third option "add a media object" could be integrated. However, this is more of a webtrees issues - Other top-level objects, such as sources, have the same three options, so I'll keep this structure for shared places.

Note that you can get rid of the second option by removing all "Quick shared place facts" in the module settings.
