### ISSUE TITLE
unknown error in webtrees

### ISSUE THREAD

**Issue by mariannevanharten** [vesta-webtrees-2-custom-modules/vesta_shared_places#73]
I wanted to temporarily widen the access to the website for a user in Webtrees, so that she can temporarily see more data. To see if I did this correctly, I masqueraded myself as this user and then visited another family member's record. That resulted in an error message (see below). What is going on and what can I do about it?

Best regards,
Marianne

`Return value of Cissee\WebtreesExt\SharedPlace::Cissee\WebtreesExt\{closure}() must be an instance of Cissee\WebtreesExt\SharedPlace, null returned …/modules_v4/vesta_shared_places/patchedWebtrees/SharedPlace.php:427
#0 [internal function]: Cissee\WebtreesExt\SharedPlace->Cissee\WebtreesExt\{closure}()
#1 …/vendor/illuminate/support/Collection.php(1120): array_map()
#2 …/modules_v4/vesta_shared_places/patchedWebtrees/SharedPlace.php(428): Illuminate\Support\Collection->map()
#3 …/modules_v4/vesta_shared_places/SharedPlacesModule.php(736): Cissee\WebtreesExt\SharedPlace->getParents()
#4 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(471): Cissee\Webtrees\Module\SharedPlaces\SharedPlacesModule->locPloc()
#5 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(420): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::locPloc()
#6 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsService.php(132): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::placPplac()
#7 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsService.php(478): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsService->resolvePlace()
#8 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(167): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsService->getAdditionalFacts()
#9 …/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended.php(193): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->hFactsTabGetAdditionalFacts()
#10 [internal function]: Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended->Cissee\Webtrees\Module\PersonalFacts\{closure}()
#11 …/vendor/illuminate/support/Collection.php(1120): array_map()
#12 …/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended.php(194): Illuminate\Support\Collection->map()
#13 …/modules_v4/vesta_personal_facts/patchedWebtrees/Module/IndividualFactsTabModule_2x.php(163): Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended->additionalFacts()
#14 …/app/Module/ModuleTabTrait.php(116): Cissee\WebtreesExt\Module\IndividualFactsTabModule_2x->getTabContent()
#15 …/app/Http/RequestHandlers/ModuleAction.php(88): Cissee\WebtreesExt\Module\IndividualFactsTabModule_2x->getTabAction()
#16 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#18 …/modules_v4/reminder/src/Modules/ReminderModule.php(98): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->process()
#20 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(226): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process()
#22 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(174): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process()
#24 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()
#26 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#28 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#31 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#33 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#35 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#37 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#38 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#39 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#41 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#43 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#45 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#47 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#49 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#51 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#53 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#55 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#57 …/app/Http/Middleware/BadBotBlocker.php(219): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#59 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#61 …/app/Http/Middleware/RegisterFactories.php(74): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process()
#63 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#64 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#66 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#67 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#68 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#69 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#70 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle()
#71 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#72 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#73 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#74 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#75 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#76 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#77 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#78 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#79 …/index.php(57): Middleland\Dispatcher->dispatch()
#80 {main}`

**Comment by ric2016** [comment]
Which webtrees version, and which Vesta version is this?
Does this error occur only when masquerading as another user?
Do you have 'broken' shared places, i.e. shared places with invalid xrefs?

**Comment by mariannevanharten** [comment]
I am using webtrees 2.0.15 and Vesta 2.0.15.4.0
I saw this error when I masquaraded as another user, but now I see it at almost all persons.
What do you mean with 'shared places with invalid xrefs'

**Comment by ric2016** [comment]
Do you have a shared place with a link to a non-existing higher-level shared place?

I'll prepare a release with a possible fix, but I'll have to test compatibility with the latest webtrees release first.

**Comment by mariannevanharten** [comment]
As far as I know, all higher-level shared places are existing places.

**Comment by ric2016** [comment]
I've fixed a related issue in the latest release 2.0.16.0.0. This may solve your issue as well (I'm not sure because it cannot actually reproduce it). Let me know if this works.

**Comment by mariannevanharten** [comment]
It seems all is working correct!
B.t.w.: the version number is 2.0.16.0.0, but my webtrees doesn't tell me that a newer webtrees is available. I still have 2.0.15

**Comment by ric2016** [comment]
That's good to hear.
I think webtrees only checks for updates once each 24 hours, so you'll get the notification tomorrow.
