### ISSUE TITLE
Empty box for SOUR:DATA:TEXT is wrongly displayed

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_shared_places#76]
Editing form for a source text is displyed only as a single line box.
![obrázok_2021-05-27_143950](https://user-images.githubusercontent.com/60657963/119827416-6379e880-bef9-11eb-8842-4c259191e556.png)

This happens only when Vesta Shared Place modul is activated and there is a source without a text.

When the module is disabled it looks normal:
![obrázok_2021-05-27_144129](https://user-images.githubusercontent.com/60657963/119827605-9e7c1c00-bef9-11eb-9aee-b1a2b2854a77.png)

Perhaps this [forum thread](https://www.webtrees.net/index.php/en/forum/help-for-2-0/35727-undo-installation-2-16) was something related to this.

**Comment by ric2016** [comment]
Fixed in Release 2.0.16.1.1.
