### ISSUE TITLE
Option: Only expand first shared place initially

### ISSUE THREAD

**Issue by ric2016** [vesta-webtrees-2-custom-modules/vesta_shared_places#8]
(even if places are different)

**Comment by Manja-S** [comment]
I would prefer to be able to set a preference for expanding shared places, similar to the options for notes and sources in 
Control panel => Manage family trees => Preferences. An option to expand only the first shared place could be added to the 'yes' and 'no' options.

**Comment by ric2016** [comment]
This is already configurable in the module config:
"Automatically expand shared place data"

Or do you miss the option to set it per tree?

**Comment by Manja-S** [comment]
Thank you! I found the option and changed it.
